# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(766, 644)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/Ahsan(BSCS-3B)/imp documents/ahsan_pic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        Dialog.setAccessibleDescription("")
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(226, 255, 217);")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 580, 311, 61))
        self.groupBox_4.setStyleSheet("color: rgb(0, 85, 0);")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.save_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.save_btn.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.save_btn.setStyleSheet("background-color: rgb(117, 255, 126);")
        self.save_btn.setObjectName("save_btn")
        self.cancel_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.cancel_btn.setGeometry(QtCore.QRect(160, 10, 141, 41))
        self.cancel_btn.setStyleSheet("background-color: rgb(255, 78, 81);")
        self.cancel_btn.setObjectName("cancel_btn")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 240, 311, 341))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QListView{\n"
"    background-color: rgb(243, 213, 255);\n"
"}")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stu_info = QtWidgets.QListWidget(self.groupBox_3)
        self.stu_info.setObjectName("stu_info")
        self.gridLayout_3.addWidget(self.stu_info, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setMidLineWidth(2)
        self.label_2.setObjectName("label_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 580, 431, 61))
        self.groupBox_5.setStyleSheet("color: rgb(0, 85, 0);")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.submit_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.submit_btn.setGeometry(QtCore.QRect(10, 10, 191, 41))
        self.submit_btn.setStyleSheet("background-color: rgb(160, 255, 198);\n"
"background-color: rgb(179, 249, 255);")
        self.submit_btn.setObjectName("submit_btn")
        self.clear_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.clear_btn.setGeometry(QtCore.QRect(230, 10, 191, 41))
        self.clear_btn.setStyleSheet("background-color: rgb(67, 135, 203);\n"
"background-color: rgb(255, 170, 127);")
        self.clear_btn.setObjectName("clear_btn")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 432, 341))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QLabel{\n"
"    color: rgb(0, 85, 0);\n"
"    background-color: rgb(255, 255, 172);\n"
"}\n"
"QLineEdit, QSpinBox, QRadioButton, QCalendarWidget, QCheckBox, QComboBox, QTimeEdit{\n"
"    \n"
"    background-color: rgb(243, 213, 255);\n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.id_spin = QtWidgets.QSpinBox(self.groupBox)
        self.id_spin.setObjectName("id_spin")
        self.gridLayout.addWidget(self.id_spin, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.name_txt = QtWidgets.QLineEdit(self.groupBox)
        self.name_txt.setObjectName("name_txt")
        self.gridLayout.addWidget(self.name_txt, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.age_spin = QtWidgets.QSpinBox(self.groupBox)
        self.age_spin.setObjectName("age_spin")
        self.gridLayout.addWidget(self.age_spin, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gm_rb = QtWidgets.QRadioButton(self.groupBox)
        self.gm_rb.setObjectName("gm_rb")
        self.gridLayout.addWidget(self.gm_rb, 3, 1, 1, 1)
        self.gf_rb = QtWidgets.QRadioButton(self.groupBox)
        self.gf_rb.setCheckable(True)
        self.gf_rb.setChecked(False)
        self.gf_rb.setAutoRepeat(False)
        self.gf_rb.setObjectName("gf_rb")
        self.gridLayout.addWidget(self.gf_rb, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.dob_cal = QtWidgets.QCalendarWidget(self.groupBox)
        self.dob_cal.setStyleSheet("background-color: rgb(243, 255, 111);\n"
"background-color: rgb(243, 196, 255);")
        self.dob_cal.setObjectName("dob_cal")
        self.gridLayout.addWidget(self.dob_cal, 4, 1, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 390, 431, 191))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 85, 0);\n"
"    background-color: rgb(255, 255, 172);\n"
"}\n"
"QLineEdit, QSpinBox, QRadioButton, QCalendarWidget, QCheckBox, QComboBox, QTimeEdit{\n"
"    \n"
"    background-color: rgb(243, 213, 255);\n"
"}")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.to_time = QtWidgets.QTimeEdit(self.groupBox_2)
        self.to_time.setObjectName("to_time")
        self.gridLayout_2.addWidget(self.to_time, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.from_time = QtWidgets.QTimeEdit(self.groupBox_2)
        self.from_time.setObjectName("from_time")
        self.gridLayout_2.addWidget(self.from_time, 1, 1, 1, 1)
        self.class_co = QtWidgets.QComboBox(self.groupBox_2)
        self.class_co.setObjectName("class_co")
        self.class_co.addItem("")
        self.class_co.addItem("")
        self.class_co.addItem("")
        self.class_co.addItem("")
        self.class_co.addItem("")
        self.class_co.addItem("")
        self.class_co.addItem("")
        self.gridLayout_2.addWidget(self.class_co, 2, 1, 1, 3)
        self.dockWidget_2 = QtWidgets.QDockWidget(self.groupBox_2)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.sci_ck = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.sci_ck.setGeometry(QtCore.QRect(140, 7, 81, 17))
        self.sci_ck.setObjectName("sci_ck")
        self.math_ck = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.math_ck.setGeometry(QtCore.QRect(140, 30, 81, 17))
        self.math_ck.setObjectName("math_ck")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_8.setGeometry(QtCore.QRect(3, 7, 131, 41))
        self.label_8.setObjectName("label_8")
        self.urdu_ck = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.urdu_ck.setGeometry(QtCore.QRect(230, 7, 81, 17))
        self.urdu_ck.setObjectName("urdu_ck")
        self.isl_ck = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.isl_ck.setGeometry(QtCore.QRect(230, 30, 81, 17))
        self.isl_ck.setObjectName("isl_ck")
        self.eng_ck = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.eng_ck.setGeometry(QtCore.QRect(320, 30, 81, 17))
        self.eng_ck.setObjectName("eng_ck")
        self.phy_ck = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.phy_ck.setGeometry(QtCore.QRect(320, 10, 81, 17))
        self.phy_ck.setObjectName("phy_ck")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.gridLayout_2.addWidget(self.dockWidget_2, 3, 0, 1, 4)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(450, 60, 311, 181))
        self.frame.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(223, 255, 19, 255), stop:0.16 rgba(91, 136, 22, 255), stop:0.225 rgba(64, 166, 41, 255), stop:0.285 rgba(74, 204, 83, 255), stop:0.345 rgba(109, 235, 102, 255), stop:0.415 rgba(114, 245, 112, 255), stop:0.52 rgba(76, 181, 209, 255), stop:0.57 rgba(51, 164, 187, 255), stop:0.635 rgba(42, 115, 168, 255), stop:0.695 rgba(75, 68, 202, 255), stop:0.75 rgba(116, 86, 218, 255), stop:0.815 rgba(155, 73, 208, 255), stop:0.88 rgba(187, 51, 120, 255), stop:0.935 rgba(137, 26, 54, 255), stop:1 rgba(202, 255, 19, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(174, 247, 255);")
        self.label_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_12.setMidLineWidth(2)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(190, 110, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 85, 255);")
        self.label_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_14.setMidLineWidth(2)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(80, 60, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(33, 159, 255);")
        self.label_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_13.setMidLineWidth(2)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Click Coatching Centre"))
        self.save_btn.setText(_translate("Dialog", "SAVE FORM"))
        self.cancel_btn.setText(_translate("Dialog", "DISCARD FORM"))
        self.groupBox_3.setTitle(_translate("Dialog", "Student Info"))
        self.label_2.setText(_translate("Dialog", "STUDENT ADDMISSION FORM"))
        self.submit_btn.setText(_translate("Dialog", "SUBMIT"))
        self.clear_btn.setText(_translate("Dialog", "CLEAR ALL"))
        self.groupBox.setTitle(_translate("Dialog", "Personal Info"))
        self.label_11.setText(_translate("Dialog", "  ID:"))
        self.label.setText(_translate("Dialog", "  NAME:"))
        self.label_3.setText(_translate("Dialog", "  AGE:"))
        self.label_4.setText(_translate("Dialog", "  GENDER:"))
        self.gm_rb.setText(_translate("Dialog", "MALE"))
        self.gf_rb.setText(_translate("Dialog", "FEMALE"))
        self.label_5.setText(_translate("Dialog", "  DATE OF BIRTH:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Class Info"))
        self.label_9.setText(_translate("Dialog", "  TO"))
        self.label_10.setText(_translate("Dialog", "  FROM"))
        self.label_7.setText(_translate("Dialog", "  TIMING:"))
        self.label_6.setText(_translate("Dialog", "  CLASS:"))
        self.class_co.setItemText(0, _translate("Dialog", "Select Class"))
        self.class_co.setItemText(1, _translate("Dialog", "9th"))
        self.class_co.setItemText(2, _translate("Dialog", "10th"))
        self.class_co.setItemText(3, _translate("Dialog", "11h"))
        self.class_co.setItemText(4, _translate("Dialog", "12th"))
        self.class_co.setItemText(5, _translate("Dialog", "MCAT"))
        self.class_co.setItemText(6, _translate("Dialog", "ECAT"))
        self.dockWidget_2.setWindowTitle(_translate("Dialog", "Subjects"))
        self.sci_ck.setText(_translate("Dialog", "Science"))
        self.math_ck.setText(_translate("Dialog", "Math"))
        self.label_8.setText(_translate("Dialog", "   Subjects:"))
        self.urdu_ck.setText(_translate("Dialog", "Urdu"))
        self.isl_ck.setText(_translate("Dialog", "Islaiat"))
        self.eng_ck.setText(_translate("Dialog", "English"))
        self.phy_ck.setText(_translate("Dialog", "Physics"))
        self.label_12.setText(_translate("Dialog", "CLICK"))
        self.label_14.setText(_translate("Dialog", "CENTRE"))
        self.label_13.setText(_translate("Dialog", "COACHING"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

